In [6]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)


In [12]:
# simple ID array and slicing
t = np.array([0.,1.,2.,3.,4.,5.,6.,])

pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0],t[1],t[-1])
print(t[2:5])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.]


In [24]:
t = tf.constant([[1.,2., 3.],[3.,4., 5.], [5.,6.,7.]])
tf.shape(t).numpy()
"""
axis는 가장 안쪽의 축이 가장 큰 수
4차원인 경우에 가장 안쪽의 축이 axis=3
"""
t2 = tf.constant([[2.],[1.],[1.]])
tf.matmul(t,t2)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 7.],
       [15.],
       [23.]], dtype=float32)>

In [27]:
# Broadcasting
# rank가 달라서 덧셈 계산이 안되는 경우에 자동으로 맞춰주는 것

matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant(3.)

print((matrix1+matrix2).numpy())

[[4. 5.]]


In [35]:
# reduce_mean
x = [[1.,2., 3.],
     [3.,4., 1.]]
print(tf.reduce_mean(x).numpy())
print(tf.reduce_mean(x, axis=0).numpy())
print(tf.reduce_mean(x, axis=1).numpy())
print(tf.reduce_sum(x).numpy())
print(tf.reduce_sum(x,axis=0).numpy())
print(tf.reduce_sum(x,axis=1).numpy())
print(tf.argmax(x,axis=0).numpy())
print(tf.argmax(x,axis=1).numpy())

2.3333333
[2. 3. 2.]
[2.        2.6666667]
14.0
[4. 6. 4.]
[6. 8.]
[1 1 0]
[2 1]


In [37]:
# 가장 많이 사용하는 Reshape
t = np.array([[[0,1,2],
               [3,4,5]],
               [[6,7,8],
                [9,10,11]]])
t.shape

(2, 2, 3)

In [52]:
print(tf.reshape(t, shape=[-1,3]).numpy()) # -1은 알아서 정해라
print(tf.squeeze([[0],[1],[2]]).numpy())
print(tf.expand_dims([0],1).numpy())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[0]]


In [59]:
t = tf.one_hot([[0],[1],[2],[0],[3]], depth=4).numpy()
print(t)
tf.reshape(t, shape=(-1,4)).numpy()

[[[1. 0. 0. 0.]]

 [[0. 1. 0. 0.]]

 [[0. 0. 1. 0.]]

 [[1. 0. 0. 0.]]

 [[0. 0. 0. 1.]]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [64]:
# casting
tf.cast([1.8,2.3,3.4,4.5], tf.int32).numpy()
# stack
x = [1,2]
y = [2,3]
z = [3,4]
print(tf.stack([x,y,z]).numpy())
print(tf.stack([x,y,z],axis=1).numpy())

[[1 2]
 [2 3]
 [3 4]]
[[1 2 3]
 [2 3 4]]


In [65]:
for x, y in zip([1,2,3],[4,5,6]):
  print(x,y)

1 4
2 5
3 6
